### ISSUE TITLE
Hãy liệt kê tất cả những kiểu dữ liệu nguyên thuỷ 

### ISSUE THREAD

**Issue by Jacobvu84** [thuyvt249/JAVA#1]
Primitive Data Type: Kiểu dữ liệu nguyên thuỷ

**Comment by thuyvt249** [comment]
Có 8 kiểu dữ liệu nguyên thủy:
1. byte
2. short
3. int
4. long
5. float
6. double
7. boolean
8. char

**Comment by Jacobvu84** [comment]
<img width="673" alt="image" src="https://user-images.githubusercontent.com/983936/105453200-49619c80-5cb2-11eb-8d54-1c91980e5fbe.png">

**Comment by Jacobvu84** [comment]
Cách tiếp cận vấn đề:

Đặt các câu hỏi làm rõ vấn đề.
- Kiểu là gì?
- Dữ liệu là gì?
- Nguyên Thuỷ là gì?
- Ngoài kiểu dữ liệu nguyên thuỷ còn kiểu dữ liệu nào khác ?

Em hãy trả lời các câu hỏi trên

**Comment by thuyvt249** [comment]
**- Kiểu là gì?**
Kiểu là một cách phân loại dữ liệu thành từng nhóm riêng biệt, mỗi 1 kiểu dữ liệu cung cấp một miền giá trị khác nhau mà một biến thuộc kiểu đó có thể nhận được. 
Ví dụ về miền giá trị của kiểu dữ liệu:
+ Miền giá trị của kiểu byte là từ -128 tới  127.
+ Miền giá trị của kiểu short là từ -32768 tới 32767.
+ Miền giá trị của kiểu int là từ -2147483648 tới 2147483647.
+ Miền giá trị của kiểu long là từ -9223372036854775808 tới 9223372036854775807

**- Dữ liệu là gì?**
Dữ liệu là các thông tin được nhập vào và được mã hóa dưới dạng nhị phân

**- Nguyên Thủy là gì?**
Nguyên Thủy là những dữ liệu không thể tách nhỏ hoặc không thể hình thành từ những dữ liệu khác. Có thể sử dụng kiểu dữ liệu nguyên thủy để xây dựng nên những kiểu dữ liệu khác

**Ngoài kiểu dữ liệu nguyên thuỷ còn kiểu dữ liệu nào khác ?**
Có kiểu dữ liệu tham chiếu ví dụ: string, array, và các class mình tạo ra đều là dữ liệu tham chiếu.

=> Em có 1 số câu hỏi ạ:
1. class là gì? 
2. Kiểu dữ liệu tham chiếu có phải được tạo nên từ kiểu dữ liệu nguyên thủy không ạ?

**Comment by Jacobvu84** [comment]
```
Kiểu dữ liệu tham chiếu có phải được tạo nên từ kiểu dữ liệu nguyên thủy không ạ? 
```
Em hoàn toàn chính xác trong nhận định của mình nhưng chưa đủ. **Đúng** mà chưa đủ thôi. 

- Class: Là kiểu dữ liệu do người dùng _tự định nghĩa_, tự viết ra. 
- Class chính là kiểu dữ liệu tham chiếu. Tại sao gọi nó là Kiểu dữ liệu THAM CHIẾU. ( Sẽ giải thích bài học tiếp theo).
   - String là một class nên nó cũng là kiểu dữ liệu tham chiếu. 
   - Array là một khác niệm khác, nó không nằm trong phạm vi bài học. Nó không phải là kiểu dữ liệu. (Sau này học tới Array sẽ tìm hiểu kỹ hơn)

Đối với kiểu dữ liệu nguyên thuỷ thì ứng với mỗi kiểu dữ liệu nguyên thuỷ ta có những phép toán tương ứng trên kiểu đó. 
Ví dụ: kiểu int thì có các phép toán (operator) như cộng, trừ, nhân, lấy nguyên, lấy dư.

Còn class là kiểu dữ liệu do người dùng tự định nghĩa nên các phép toán ( cách xử lý dữ liệu) cũng do người dùng tự viết. ( Sau này học phần tạo class và các method trong class đó sẽ phân tích kỹ hơn)
