### ISSUE TITLE
Viết class để quản lý tiền điện

### ISSUE THREAD

**Issue by Jacobvu84** [thuyvt249/JAVA#10]
Yêu cầu:

Kiểm tra chỉ số tiêu thụ điện trong tháng có lớn hơn 200 kwh không?

Dùng class. máy tính

**Comment by thuyvt249** [comment]
```package com.company;

public class ElectricBill {
    private String billID;
    private String fullName;
    private String address;
    private int firt;
    private int last;
    private int price;
    private Calculator calculator;

    public ElectricBill(int firt, int last) {
        this.firt = firt;
        this.last = last;
        calculator = new Calculator(last, firt);
    }

    public int getTotalElectricUnit(){
        return calculator.subtraction();
    }
}
```

```package com.company;

class TestCalculator {
    public static void main(String[] args) {
        ElectricBill checkBill = new ElectricBill(500,700);
        int getTotalElectricUnit = checkBill.getTotalElectricUnit();
        if (checkBill.getTotalElectricUnit()>200){
            System.out.println("Chỉ số tiêu thu điện trong tháng lớn hơn 200kwh ");
        } else if (checkBill.getTotalElectricUnit() == 200){
            System.out.println("Chỉ số tiêu thu điện trong tháng bằng 200kwh ");
        } else {
            System.out.println("Chỉ số tiêu thụ điện trong tháng nhỏ hơn 200kwh");
        }
    }
}
```

**Comment by Jacobvu84** [comment]
Good lắm. em rất hiểu cách sử dụng. 

Từ cái hiểu trước đây của em về class là Class được tạo bởi các kiểu dữ liệu nguyên thuỷ. Thì giờ đây qua ví dụ này em biết thêm là Class có thể được tạo bởi các class khác.

```
public class ElectricBill {
    private String billID;
     .....
    private Calculator calculator;
```
như trong ví dụ này là em đã dùng đối tượng của Calculator class như là một thuộc tính để cấu thành lên ElectricBill class

**Comment by Jacobvu84** [comment]
Từ ví dụ này, ta thấy nó xuất hiện thêm một cái mới đó chính là các MỐI QUAN HỆ (Relationship) giữa các class

Chi tiết hơn về vấn đề này chúng ta sẽ chuyển qua một ticket mới.

**Comment by Jacobvu84** [comment]
@thuyvt249 

Trong ví dụ này của em. Nó là một quan hệ "hợp thành" ( composite).Hay còn biết tới tên gọi là **Has-A relationship**, mối quan hệ chứa nhau.

- Calculator đóng vai trò là một nhân tố ( thuộc tính) tạo nên ElectricBill.

Nhưng xét về mối quan hệ thực tế trong đời sống. Tờ hoá đơn tiền điện ko có liên quan giờ tới máy tính cả. Mặc dù các con số tính toán trên tờ hoá đơn đó dùng để tính số liêu. Nhưng cơ bản nó là 2 đối tượng độc lập. 

Nên trong tình huống này việc sử dụng như vậy là không hợp lý.

**Comment by Jacobvu84** [comment]
Một tình huống như sau. Người quản lý tiền điện quyết định sẽ giảm 10 hoá đơn tiền điện cho những chủ hộ trên 100 tuổi. 

Ta sẽ giải quyết bài toán này như thế nào?

Nếu cho thêm thuộc tính tuổi của chủ hộ vào. Nó dường như ko liên quan lắm tới Hoá đơn tiền điện, mặc dù có thể làm như vậy.

```
public class ElectricBill {
    private String billID;
    private String fullName;
    private int ageOfHolder
```

Lúc này ta sẽ gộp 2 thuộc tính 

```
    private String fullName;
    private int ageOfHolder
``` 

để tạo thành class mới có tên là Customer

```
public class Customer {
    private String customerID;
    private String fullName;
    private int ageOfHolder
```

Sau đó ta sử dụng Customer trong ElectricBill theo quan hệ `ElectricBill has a Customer`

```
public class ElectricBill {
    private String billID;
    private Customer customer;
 
```
