### ISSUE TITLE
Các hành vi xử lý của máy tính dựa trên dữ liệu kiểu int

### ISSUE THREAD

**Issue by Jacobvu84** [thuyvt249/JAVA#2]
Máy tính làm việc dựa trên việc xử lý dữ liệu. Tuỳ thuộc vào kiểu dữ liệu khác nhau thì máy tính có những cách xử lý khác nhau. Nghĩa là đi tương ứng với kiểu dữ liệu là A thì máy tính có thể làm được những gì trên đó.

Vậy hãy liệt kê các công việc mà máy tính có thể thao tác, xử lý với dữ liệu thuộc kiểu int

**Comment by thuyvt249** [comment]
Các công việc mà máy tính có thể thao tác, xử lý với dữ liệu thuộc kiểu int:
- Thực hiện các toán tử số học cộng, trừ, nhân, chia...
- Các toán tử gán (Em chưa hiểu về phần này ạ)
- Toán tử một ngôi (Em chưa hiểu về phần này ạ)
- 
=> Em đọc tài liệu thấy từ toán hạng được nhắc tới nhiều. Vậy toán tử và toán hạng khác gì nhau ạ?

**Comment by Jacobvu84** [comment]
Toán tử: Nói đầy đủ là toán tử cộng, toán tử trừ, toán tử nhân... hay nói các quen thuộc như hồi đi học phổ thông nó đc gọi là "phép tính" ví dụ phép tính cộng, phép tính trừ, phép tính nhân....

**Comment by Jacobvu84** [comment]
Toán hạng: hay còn gọi là số hạng. Trong một biểu thức toán học sẽ bao gồm toán tử (phép tính) và các toán hạng (số hạng) tương ứng với phép tính đó.

Ví dụ 1: Ta có một biểu thức toán học như sau:
2+3=5

- Toán tử ( tiếng Anh: Operator) trong ví dụ trên là phép cộng
- Toán hạng: Số hạng tham gia vào phép cộng trên gồm hai số hạng là 2 và 3.

Ví dụ 2: Có một dãy số: 1 6 9 2 5 ... thì mỗi số trong dãy số trên cũng gọi là một số hạng. Số hạng ở vị trí thứ 3 có giá trị là 9

**Comment by Jacobvu84** [comment]
Gán: là cách biểu thị hay thay thế cái này bằng cái kia. Trong đời sống nickname là một kiểu phép gán thay thế cho tên thật. Ví dụ. Tên thầy là Linh và có nickname là boydeptrai. Vậy cứ nói đến boydeptrai là người ta sẽ liên tưởng đến thầy Linh.

Trong toán học nó chính là dấu =
- Ví dụ: Ta có phép toán là: 2+3. Đây là cách viết tường minh, rõ ràng và rất cụ thể.

Tuy nhiên, ta có thể viết lại như sau.
Thay vì viết là 2 ta sẽ đặt (biểu thị / biểu diễn) số 2 bằng chữ x và số 3 bằng chữ y:

Ta sẽ viết x = 2;  y = 3;
Ta nói gán giá trị 2 cho x và gán giá trị 3 cho y

Viết lại phép toán: x + y

Kết quả của bài toán trên là tổng: a = x + y

Ta nói gán kết quả của phép cộng x + y cho a. Trong lập trình người ta sẽ gọi nó là "trả về" ( return) kết quả cộng cho a.

Sau này học về phần biến số sẽ làm rõ thêm.
