### ISSUE TITLE
Bài 03: Viết chương trình in ra ký tự 'A' và in ra số ngày trong tuần

### ISSUE THREAD

**Issue by Jacobvu84** [thuyvt249/JAVA#3]
Cú pháp để khai báo một biến và gán giá trị 

```
<kiểu dữ liệu> <tên biến> = <giá trị>
```

Ví dụ

char kytu = 'A';
byte soNgayTrongTuan = 7;

Để in ra được giá trị thông qua biến số. 

```
System.out.println("Ký tự cần in ra là: " + kytu);
System.out.println("Số ngày trong tuần là: "+soNgayTrongTuan);
```

**Comment by Jacobvu84** [comment]
Bài tập

Viết chương trình in ra số ngày trong năm

**Comment by thuyvt249** [comment]
`public class Main {

    public static void main(String[] args) {
	// write your code here
        int soNgayTrongNam = 365;
        System.out.println("Số ngày trong năm là: " +soNgayTrongNam );
    }
}`

**Comment by thuyvt249** [comment]
Với số hạng 365 em có thể dùng kiểu dữ liệu short để viết chương trình nữa ạ. Vậy khi gặp những case có thể dùng được cả kiểu dữ liệu byte, short, int thì em nên chọn kiểu dữ liệu có miền giá trị đúng nhất hay em có thể mặc định chọn kiểu int ạ?

**Comment by Jacobvu84** [comment]
Em nên chọn cái đúng nhất để tiết kiệm bộ nhớ cho máy tính. Vì bộ nhớ nó không phải vô hạn.

Em hãy tưởng tượng: em đi du lịch nhóm bạn. Nhóm em có 4 người. Thì e thuê phòng mấy giường. ? 

Hãy nghĩ. Bộ nhớ máy tính là toà nhà khách sạn. Nếu có 4 người e thuê 10 phòng. Thì sẽ lãng phí 6 phòng mà tốn chỉ phí. Bởi vậy tùy thuộc dữ liệu mình để phục vụ cho mục đích gì ta nên chọn kiểu phù hợp nhất.

**Comment by thuyvt249** [comment]
Phép tính cộng 2 số:

`public class Main {

    public static void main(String[] args) {
	// write your code here
        int x = 2;
        int y = 5;
        System.out.println(x+y);
    }
}`
