### ISSUE TITLE
Quy ước trong ngôn ngữ lập trình java

### ISSUE THREAD

**Issue by Jacobvu84** [thuyvt249/JAVA#8]
Why Have Code Conventions
Code conventions are important to programmers for a number of reasons:

- 80% of the lifetime cost of a piece of software goes to maintenance.
- Hardly any software is maintained for its whole life by the original author.
- Code conventions improve the readability of the software, allowing engineers to understand new code more quickly and thoroughly.
- If you ship your source code as a product, you need to make sure it is as well packaged and clean as any other product you create.

Tham khảo: https://www.oracle.com/java/technologies/javase/codeconventions-introduction.html

Tại sao cần phải tuân thủ những quy ước này.
Vì một số lý do sau:

- Chi phí bảo trì phần mềm chiếm khoảng 80% trong quá trình vận hành.
- Khó có một ai đó tự phát triển và bảo trì một software cả đời của họ,
- Tăng khả năng dễ đọc của code. Giúp cho người mới có thể hiểu được code nhanh chóng và kỹ lương hơn.
- Làm sạch nó trước khi đưa nó đi đâu đó ( như một cách trân trọng bản thân, Thường tặng quà ta phải gói và bọc nó thật đẹp với nơ và hộp. Chứ ít ai cho vào túi rách rồi mang cho người khác. Của cho không bằng cách cho :D. Viẹc làm code mình sạch đẹp, ko mùi là một cách thể hiện sự chuyên nghiệp)

**Comment by Jacobvu84** [comment]
Bài tập:

Tìm hiểu về quy ước đặt tên cho Packages, Class, Method, Variable ( biến), Object ( đối tượng)

**Comment by thuyvt249** [comment]
**Quy ước đặt tên cho Packages:**
- Package thường được đặt tên giống như đặt tên thư mục trên ổ đĩa tức là sẽ được bắt đầu bằng tên có phạm vi lớn cho đến phạm vi nhỏ dần.
- Các ký tự trong định danh package là chữ, số in thường.
- Thông thường ta sẽ đặt tên package với các phạm vi và thứ tự như sau:
+ Tên tổ chức, tên miền
+ Tên công ty
+ Tên dự án
+ Tên module (sau đấy là các các module con (nếu có)
+ Tên chức năng module.
**ex:** com.ttc.learnjava

**Quy ước đặt tên cho Class**
- Tên Class phải được đặt bằng tiếng Anh, đúng chính tả và phải là danh từ (Cần sử dụng tên nào đó để có thể thể hiện được đối tượng mà mình đang muốn mô hình hóa)
- Đặt tên theo kiểu “Pascal case” : các từ được phân tách bởi việc ghi hoa kí tự đầu tiên của mỗi từ và kí tự đầu tiên phải được ghi hoa
- Tránh dùng tên trùng với các kiểu dữ liệu đã được định nghĩa sẵn (ví dụ như Number, String, Float…)
- Tên class phải trùng với tên file và mỗi file chỉ chứa một class
**ex:** Calculator

**Quy ước đặt tên cho Method**
- Tên Method trong Java nên được áp dụng theo kiểu Camel case - Chữ cái đầu tiên sẽ được viết thường, các từ còn lại sẽ được viết hoa chữ cái đầu tiên
- Nên sử dụng các động từ để mô tả những gì phương thức sẽ làm
**ex:** addition

**Quy ước đặt tên cho Biến**
- Tên biến cũng được áp dụng theo kiểu Camel case
- Không nên bắt đầu bằng các ký tự đặc biệt như ký hiệu &, $, _ (phần này em đọc nhiều trang thì có trang viết là ko được dùng, có trang viết là được dùng nên em không biết như thế nào mới đúng ạ)
- Dùng các từ dễ nhớ
**ex:**numberA

**Quy ước đặt tên cho đối tượng**
- Đặt tên theo kiểu Camel case. Cần sử dụng tên nào đó để có thể thể hiện được đối tượng mà mình muốn tạo)
**ex:** calculatorTest

**Comment by Jacobvu84** [comment]
Sao ko lấy ví dụ cho mỗi loại. Có phải nó sẽ rõ nét hơn không?

**Comment by Jacobvu84** [comment]
```
Không nên bắt đầu bằng các ký tự đặc biệt như ký hiệu &, $, _ (phần này em đọc nhiều trang thì có trang viết là ko được dùng, có trang viết là được dùng nên em không biết như thế nào mới đúng ạ)
```

Thông thường các trình soạn thảo (IDE) đã hỗ trợ việc complier tự động nên nếu vi phạm các nguyên tắc nó sẽ báo lỗi ngay. 

Trong trường hợp nó không báo lỗi biên dịch, nghĩa là có thể dùng thì cũng không nên dùng **các ký tự đặc biệt** 

Về dấu gạch dưới _ hoàn toàn có thể dùng. Cái này nó phụ thuộc vào phong cách code của từng người. 

Giống như mình đặt tiền tố mà cứ gõ tiền tố đó đầu tiên tự khác nó sẽ xuất hiện gợi ý những phần tử thuộc trong nhóm mà mình cần tìm.

Ví dụ tất cả các biến đều bắt đầu bởi dấu gạch dưới _age, _name, _address,.... thì viết code, mình chỉ cần gõ gạch dưới _ thì trình soạn thảo sẽ tự động liệt kê toàn bộ các biến đã khai báo trong class. 

![image](https://user-images.githubusercontent.com/983936/106113693-57675f80-6181-11eb-996a-4c6702bd7e5c.png)

Nó sẽ giúp mình dễ dàng hơn việc lựa chọn các biến.

**Comment by thuyvt249** [comment]
> Sao ko lấy ví dụ cho mỗi loại. Có phải nó sẽ rõ nét hơn không?

Dạ vâng em đã update lại ạ

**Comment by thuyvt249** [comment]
```Ví dụ tất cả các biến đều bắt đầu bởi dấu gạch dưới _age, _name, _address,.... thì viết code, mình chỉ cần gõ gạch dưới _ thì trình soạn thảo sẽ tự động liệt kê toàn bộ các biến đã khai báo trong class.```

Dạ vâng em hiểu chỗ này rồi ạ
